from enum import Enum


class AccountSupportTypeType(str, Enum):
    BROKERDEALER = "BROKERDEALER"
    FAMILYINVVEHICLE = "FAMILYINVVEHICLE"
    FINANCIALINSTITUTION = "FINANCIALINSTITUTION"
    LICENSEDADVISOR = "LICENSEDADVISOR"
    OPERATINGBUSINESS = "OPERATINGBUSINESS"
    PROPRIETARYTRADING = "PROPRIETARYTRADING"

    def __str__(self) -> str:
        return str(self.value)
