from enum import Enum


class AutomatedWrapFeeDetailsTypeType(str, Enum):
    ANNUALFLATFEE = "ANNUALFLATFEE"
    ANNUALFLATFEE_MONTHLY = "ANNUALFLATFEE_MONTHLY"
    ANNUALFLATFEE_QUATERLY = "ANNUALFLATFEE_QUATERLY"
    BLENDEDPERCENTOFEQUITY = "BLENDEDPERCENTOFEQUITY"
    BLENDEDPERCENTOFEQUITY_MONTHLY = "BLENDEDPERCENTOFEQUITY_MONTHLY"
    BLENDEDPERCENTOFEQUITY_QUARTERLY = "BLENDEDPERCENTOFEQUITY_QUARTERLY"
    INVOICE_LIMIT = "INVOICE_LIMIT"
    INVOICE_LIMIT_Q = "INVOICE_LIMIT_Q"
    PERCENTOFEQUITY = "PERCENTOFEQUITY"
    PERCENTOFEQUITY_MONTHLY = "PERCENTOFEQUITY_MONTHLY"
    PERCENTOFEQUITY_QUARTERLY = "PERCENTOFEQUITY_QUARTERLY"
    PERCENTOFEQUITY_QUATERLY = "PERCENTOFEQUITY_QUATERLY"
    PERCENTOFPROFIT = "PERCENTOFPROFIT"
    PERCENTOFPROFIT_QUARTER = "PERCENTOFPROFIT_QUARTER"
    PERTRADE = "PERTRADE"

    def __str__(self) -> str:
        return str(self.value)
