from enum import Enum


class DepositFundsInstructionIraDepositDetailFromIraType(str, Enum):
    EDUCATION = "EDUCATION"
    NONE = "NONE"
    RETIREMENT_SAVING_PLAN = "RETIREMENT_SAVING_PLAN"
    ROLLOVER = "ROLLOVER"
    ROTH = "ROTH"
    ROTH_INHERITED = "ROTH_INHERITED"
    SEP = "SEP"
    SEP_INHERITED = "SEP_INHERITED"
    SPOUSAL_RETIREMENT_SAVING_PLAN = "SPOUSAL_RETIREMENT_SAVING_PLAN"
    TAX_FREE_SAVING_ACCOUNT = "TAX_FREE_SAVING_ACCOUNT"
    TRADITIONAL = "TRADITIONAL"
    TRADITIONAL_INHERITED = "TRADITIONAL_INHERITED"

    def __str__(self) -> str:
        return str(self.value)
