from enum import Enum


class FormW8IMYEntityType(str, Enum):
    NONQUALIFIED_INTERMEDIARY = "NONQUALIFIED_INTERMEDIARY"
    NONWITHHOLDING_FOREIGN_GRANTOR_TRUST = "NONWITHHOLDING_FOREIGN_GRANTOR_TRUST"
    NONWITHHOLDING_FOREIGN_PARTNERSHIP = "NONWITHHOLDING_FOREIGN_PARTNERSHIP"
    NONWITHHOLDING_FOREIGN_SIMPLE_TRUST = "NONWITHHOLDING_FOREIGN_SIMPLE_TRUST"
    QUALIFIED_INTERMEDIARY = "QUALIFIED_INTERMEDIARY"
    TERRITORY_FINANCIAL = "TERRITORY_FINANCIAL"
    US_BRANCH = "US_BRANCH"
    WITHHOLDING_FOREIGN_PARTNERSHIP = "WITHHOLDING_FOREIGN_PARTNERSHIP"
    WITHHOLDING_FOREIGN_TRUST = "WITHHOLDING_FOREIGN_TRUST"

    def __str__(self) -> str:
        return str(self.value)
