from enum import Enum


class FormW8BENEEntityType(str, Enum):
    CENTRAL_BANK_OF_ISSUE = "CENTRAL_BANK_OF_ISSUE"
    COMPLEX_TRUST = "COMPLEX_TRUST"
    CORPORATION = "CORPORATION"
    DISREGARDED_ENTITY = "DISREGARDED_ENTITY"
    ESTATE = "ESTATE"
    GOVERNMENT = "GOVERNMENT"
    GRANTOR_TRUST = "GRANTOR_TRUST"
    PARTNERSHIP = "PARTNERSHIP"
    PRIVATE_FOUNDATION = "PRIVATE_FOUNDATION"
    SIMPLE_TRUST = "SIMPLE_TRUST"
    TAX_EXEMPT_ORGANIZATION = "TAX_EXEMPT_ORGANIZATION"

    def __str__(self) -> str:
        return str(self.value)
