from enum import Enum


class FormW8IMYFatcaStatus(str, Enum):
    ACTIVE_NFFE = "ACTIVE_NFFE"
    CERTIFIED_DEEMED_COMPLAINT_FFI = "CERTIFIED_DEEMED_COMPLAINT_FFI"
    CERTIFIED_DEEMED_COMPLAINT_LIMITED_LIFE_DEBT = "CERTIFIED_DEEMED_COMPLAINT_LIMITED_LIFE_DEBT"
    CERTIFIED_DEEMED_COMPLAINT_SPONSORED = "CERTIFIED_DEEMED_COMPLAINT_SPONSORED"
    DIRECT_REPORTING_NFFE = "DIRECT_REPORTING_NFFE"
    EXCEPTED_NONFINANCIAL_ENTITY_IN_LIQUIDATION = "EXCEPTED_NONFINANCIAL_ENTITY_IN_LIQUIDATION"
    EXCEPTED_NONFINANCIAL_GROUP_ENTITY = "EXCEPTED_NONFINANCIAL_GROUP_ENTITY"
    EXCEPTED_NONFINANCIAL_STARTUP_COMPANY = "EXCEPTED_NONFINANCIAL_STARTUP_COMPANY"
    EXCEPTED_TERRITORY_NFFE = "EXCEPTED_TERRITORY_NFFE"
    EXEMPT_RETIREMENT_PLAN = "EXEMPT_RETIREMENT_PLAN"
    FOREIGN_CENTRAL_BANK_ISSUE = "FOREIGN_CENTRAL_BANK_ISSUE"
    NONPARTICIPATING_FFI = "NONPARTICIPATING_FFI"
    NONREPORTING_IGA_FFO = "NONREPORTING_IGA_FFO"
    OWNER_DOCUMENTED_FFI = "OWNER_DOCUMENTED_FFI"
    PARTICIPATING_FFI = "PARTICIPATING_FFI"
    PASSIVE_NFFE = "PASSIVE_NFFE"
    PUBLICLY_TRADED_NFFE = "PUBLICLY_TRADED_NFFE"
    REGISTERED_DEEMED_COMPLAINT = "REGISTERED_DEEMED_COMPLAINT"
    REPORTING_MODEL1_FFI = "REPORTING_MODEL1_FFI"
    REPORTING_MODEL2_FFI = "REPORTING_MODEL2_FFI"
    RESTRICTED_DISTRIBUTOR = "RESTRICTED_DISTRIBUTOR"
    SPONSORED_DIRECT_REPORTING_NFFE = "SPONSORED_DIRECT_REPORTING_NFFE"
    SPONSORED_FFI = "SPONSORED_FFI"
    TERRITORY_FINANCIAL_INSTITUTION = "TERRITORY_FINANCIAL_INSTITUTION"

    def __str__(self) -> str:
        return str(self.value)
