from enum import Enum


class PostGwApiV1BankInstructionsBodyInstructionType(str, Enum):
    ACH_INSTRUCTION = "ACH_INSTRUCTION"
    DELETE_BANK_INSTRUCTION = "DELETE_BANK_INSTRUCTION"
    EDDA_INSTRUCTION = "EDDA_INSTRUCTION"
    PREDEFINED_DESTINATION_INSTRUCTION = "PREDEFINED_DESTINATION_INSTRUCTION"
    TRADITIONAL_BANK_INSTRUCTION_VERIFICATION = "TRADITIONAL_BANK_INSTRUCTION_VERIFICATION"

    def __str__(self) -> str:
        return str(self.value)
