from enum import Enum


class RegulatoryDetailCode(str, Enum):
    AFFILIATION = "AFFILIATION"
    AUSEXPOSURE = "AUSEXPOSURE"
    BROKERDEALER = "BROKERDEALER"
    BROKER_DEALER = "BROKER_DEALER"
    CFTCREGISTERED = "CFTCREGISTERED"
    CONTROLLER = "CONTROLLER"
    CONTROLPUBTRADED = "ControlPubTraded"
    CRIMINAL = "CRIMINAL"
    DISPUTE = "DISPUTE"
    EMPLOYEEPUBTRADE = "EmployeePubTrade"
    EMPLOYEE_BENEFIT_PLAN = "EMPLOYEE_BENEFIT_PLAN"
    EXCHANGEMEMBERSHIP = "EXCHANGEMEMBERSHIP"
    FINANCIAL_ADVISOR = "FINANCIAL_ADVISOR"
    FOREIGN_BANK = "FOREIGN_BANK"
    FOREIGN_EXCHANGE = "FOREIGN_EXCHANGE"
    FUTURES_COMMISSION_MERCHANT = "FUTURES_COMMISSION_MERCHANT"
    HIGH_RISK_CONTRIBUTION = "HIGH_RISK_CONTRIBUTION"
    IBACCOUNTS = "IBACCOUNTS"
    INVESTIGATION = "INVESTIGATION"
    MEMBERSHIP = "MEMBERSHIP"
    MONEY_TRANSMITTER = "MONEY_TRANSMITTER"
    MUTUAL_FUND = "MUTUAL_FUND"
    NON_US_INSURANCE_COMPANY = "NON_US_INSURANCE_COMPANY"
    POLITICALMILITARYDIPLOMATIC = "POLITICALMILITARYDIPLOMATIC"
    REGULATORYCONTROL = "REGULATORYCONTROL"
    STOCKCONTROL = "STOCKCONTROL"
    US_BANK = "US_BANK"
    US_DEPT = "US_DEPT"
    US_INSURANCE_COMPANY = "US_INSURANCE_COMPANY"
    US_SWAP_DEALER = "US_SWAP_DEALER"
    US_SWAP_PARTICIPANT = "US_SWAP_PARTICIPANT"

    def __str__(self) -> str:
        return str(self.value)
