from enum import Enum


class SourceOfIncomeTypeSourceType(str, Enum):
    CONSULTING = "CONSULTING"
    DISABILITY = "DISABILITY"
    INHERITANCE = "INHERITANCE"
    INTEREST = "INTEREST"
    OTHER = "OTHER"
    PENSIONANDSOCIALSECURITY = "PENSIONANDSOCIALSECURITY"
    REALESTATE = "REALESTATE"
    RENTAL = "RENTAL"
    SEVERANCE = "SEVERANCE"
    SPOUSE = "SPOUSE"
    TRADINGANDINVESTMENTS = "TRADINGANDINVESTMENTS"
    UNEMPLOYMENT = "UNEMPLOYMENT"

    def __str__(self) -> str:
        return str(self.value)
