from enum import Enum


class TitleCode(str, Enum):
    ACCOUNT_HOLDER = "Account Holder"
    BENEFICIARY = "BENEFICIARY"
    CEO = "CEO"
    COMP_OFFICER = "COMP_OFFICER"
    CONTINGENT = "CONTINGENT"
    CONTROLLING_OFFICER = "Controlling Officer"
    CUSTODIAN = "CUSTODIAN"
    CUSTODIAN_EMPLOYEE = "CUSTODIAN EMPLOYEE"
    DIRECTOR = "DIRECTOR"
    EMPLOYEE = "Employee"
    FIRST_HOLDER = "FIRST HOLDER"
    GRANTOR = "GRANTOR"
    IRA_BENEFICIARY = "IRA_BENEFICIARY"
    IRA_DECEDENT = "IRA DECEDENT"
    NON_EMPLOYEE = "NON-EMPLOYEE"
    OTHER_OFFICER = "Other Officer"
    OWNER = "OWNER"
    PARTNER = "PARTNER"
    PRINCIPAL = "PRINCIPAL"
    SECOND_HOLDER = "SECOND HOLDER"
    SECRETARY = "SECRETARY"
    SHAREHOLDER = "SHAREHOLDER"
    SIGNATORY = "SIGNATORY"
    SPOUSE = "SPOUSE"
    SUCCESSOR_CUSTODIAN = "SUCCESSOR_CUSTODIAN"
    SUCCESSOR_CUSTODIAN_EMPLOYEE = "SUCCESSOR CUSTODIAN EMPLOYEE"
    SUCCESSOR_HOLDER = "Successor Holder"
    TRADER = "TRADER"
    TREASURER = "TREASURER"
    TRUSTEE = "TRUSTEE"

    def __str__(self) -> str:
        return str(self.value)
